title: Segmentation Fault
description: Website for personal documentation, resources, guides, cheatsheets, ...
theme: just-the-docs

url: https://jotavare.github.io/

aux_links:
  GitHub: https://github.com/jotavare/jotavare.github.io
  LinkedIn: https://www.linkedin.com/in/jotavare
