title: Registry
description: Personal documentation, resources, guides, cheatsheets, ...
theme: just-the-docs

url: https://jotavare.github.io/

aux_links:
  GitHub: https://github.com/jotavare
  LinkedIn: https://www.linkedin.com/in/jotavare
  Contact: "mailto:jpoliveira.mm@gmail.com"
  /?: https://www.youtube.com/watch?v=dQw4w9WgXcQ

aux_links_new_tab: true

nav_external_links:
  - title: 🔗 Quick Reference
    url: https://quickref.me/
    hide_icon: true
    opens_in_new_tab: true
  - title: 🔗 Piscine Repository
    url: https://github.com/jotavare/42-piscine
    hide_icon: true
    opens_in_new_tab: true
  - title: 🔗 Common Core Repository
    url: https://github.com/jotavare/42-common-core
    hide_icon: true
    opens_in_new_tab: true
  - title: 🔗 One Year of 42
    url: https://www.linkedin.com/pulse/one-year-42-jo%C3%A3o-oliveira/
    hide_icon: true
    opens_in_new_tab: true
  - title: 🔗 Terminal Style CV
    url: https://jotavare.github.io/terminal-style-cv/
    hide_icon: true
    opens_in_new_tab: true
  - title: 🔗 Registry Repository
    url: https://github.com/jotavare/jotavare.github.io
    hide_icon: true
    opens_in_new_tab: true

color_scheme: dark

favicon_ico: "/assets/images/favicon.ico"

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

nav_enabled: true

nav_sort: case_sensitive

heading_anchors: false

search_enabled: true

search:
  heading_level: 2

  previews: 3

  preview_words_before: 5

  preview_words_after: 10

  tokenizer_separator: /[\s/]+/

  rel_url: true

  button: false

  focus_shortcut_key: "k"

enable_copy_code_button: true

back_to_top: true
back_to_top_text: "Back to top"

liquid:
  error_mode: strict
  strict_filters: true

footer_content: 'Copyright &copy; 2024. Distributed by an <a href="https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt">MIT license.'

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/jotavare/jotavare.github.io"
gh_edit_branch: "main"

gh_edit_view_mode: "tree"
